name: openapi-axios

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  integration-openapi-axios:
    strategy:
      matrix:
        node-version:
          - 24.x
        openapi-generator-version:
          - 7.0.0
          - 7.19.0
        axios-version:
          - 1.9.0
          - 1.10.0
          - 1.11.0
          - 1.12.0
          - 1.13.0
    uses: ./.github/workflows/test-template.yaml
    with:
      node-version: ${{ matrix.node-version }}
      openapi-generator-version: ${{ matrix.openapi-generator-version }}
      axios-version: ${{ matrix.axios-version }}
      superagent-version: ''
      test-command: 'npx jest tests/integration/e2e -t "openapi-axios"'
      cache-generated-clients: false
